import { User } from "../types/buildtrack";

// Centralized mock users - single source of truth
export const MOCK_USERS: User[] = [
  {
    id: "1",
    email: "manager@buildtrack.com",
    name: "John Manager",
    role: "manager",
    companyId: "comp-1",
    position: "Project Manager",
    phone: "555-0101",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2", 
    email: "worker@buildtrack.com",
    name: "Sarah Worker",
    role: "worker",
    companyId: "comp-1",
    position: "Construction Worker",
    phone: "555-0102",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    email: "admin@buildtrack.com", 
    name: "Alex Administrator",
    role: "admin",
    companyId: "comp-1",
    position: "System Administrator",
    phone: "555-0103",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    email: "lisa@eliteelectric.com",
    name: "Lisa Martinez",
    role: "worker",
    companyId: "comp-2",
    position: "Electrician",
    phone: "555-0104",
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    email: "admin@eliteelectric.com",
    name: "Mike Johnson",
    role: "admin",
    companyId: "comp-2",
    position: "Operations Manager",
    phone: "555-0105",
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    email: "peter@buildtrack.com",
    name: "Peter",
    role: "worker",
    companyId: "comp-1",
    position: "Site Supervisor",
    phone: "555-0106",
    createdAt: new Date().toISOString(),
  },
];
